package dawrentinghibernate;
// Generated 09-feb-2017 19:56:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private String dni;
     private String name;
     private String phone;
     private double salary;
     private Set cars = new HashSet(0);

    public Driver() {
    }

	
    public Driver(String dni, String name, String phone, double salary) {
        this.dni = dni;
        this.name = name;
        this.phone = phone;
        this.salary = salary;
    }
    public Driver(String dni, String name, String phone, double salary, Set cars) {
       this.dni = dni;
       this.name = name;
       this.phone = phone;
       this.salary = salary;
       this.cars = cars;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }
    public Set getCars() {
        return this.cars;
    }
    
    public void setCars(Set cars) {
        this.cars = cars;
    }




}


