package dawrentinghibernate;
// Generated 09-feb-2017 19:56:22 by Hibernate Tools 4.3.1



/**
 * Rental generated by hbm2java
 */
public class Rental  implements java.io.Serializable {


     private Integer idrental;
     private Car car;
     private City city;
     private String customer;

    public Rental() {
    }

    public Rental(Car car, City city, String customer) {
       this.car = car;
       this.city = city;
       this.customer = customer;
    }
   
    public Integer getIdrental() {
        return this.idrental;
    }
    
    public void setIdrental(Integer idrental) {
        this.idrental = idrental;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }




}


